### ISSUE TITLE
Ability to add a crypto media-tag from an external website

### ISSUE THREAD

**Issue by cjdelisle** [UCF-project/media-tag#10]
I have a blog post in CryptPad blog here: https://cryptpad.fr/code/#/1/view/LI8SgndbOY+NccjC88H3VA/xTeUe7qz8plSQy+UVSMaZxn5PZP90nfK-M2PaeDiAkA/ and it contains a number of Zero Knowledge images. I would like to migrate this to a post on blog.cryptpad.fr which is static HTML generated from markdown.

I would love to be able to copy/paste this content out of CryptPad into our blog generator and then add a single `<script>` tag which will render all of these media-tags without getting in the way of the website where it's embedded.

**Comment by JonRiv** [comment]
Thanks for the issue, proposed use case :

1. I copy media-tag content from your link
```
<media-tag data-attr-alt="Trolly Problem" data-crypto-key="cryptpad:jabcpGb28ii/yZ4ckHAx3/9eXqyfZEEVxcvc/1LjK3U=" src="https://cryptpad.fr/blob/8f/8f149cfded5e5dd4e29685fdb3e6d311873456530a3548ff"></media-tag>
```

2. I paste it in a body and add a script tag calling the media tag lib
```
<head>
    <script src="mediatag-distro-example.js"></script>
</head>
<body>
    <media-tag 
        data-attr-alt="Trolly Problem" 
        data-crypto-key="cryptpad:jabcpGb28ii/yZ4ckHAx3/9eXqyfZEEVxcvc/1LjK3U=" src="https://cryptpad.fr/blob/8f/8f149cfded5e5dd4e29685fdb3e6d311873456530a3548ff">
    </media-tag>
</body>
```

3. Media-tags are rendered

**Comment by Regzox** [comment]
You can call media-tag as a external library with a script tag. 
You have to add explicitly all media-tag dependencies in your page head or provide a configuration file with these dependencies.

This is the example of media-tag entire (re)definition : https://github.com/UCF-project/media-tag/blob/master/demo/webpack/configuration/configuration.js
