### ISSUE TITLE
Expose decrypted blob

### ISSUE THREAD

**Issue by ansuz** [UCF-project/media-tag#2]
We would like to be able to inspect/reuse the blob once it has been fetched and decrypted. This would give us the ability to extract metadata from the blob, such as its file type, name, and anything else encoded at the time of its encryption.

**Comment by Regzox** [comment]
See the answer given in #1 

```
			# THE DECRYPTED BLOB CAN BE SENT BY EVENT AND CATCH ANYWHERE

			const decryptionEvent = new Event('decryption'); 
			decryptionEvent.blob = new Blob([binStr], {
				type: mediaObject.getMimeType()
			});
			window.document.dispatchEvent(decryptionEvent);

```
