### ISSUE TITLE
Allow decryption methods to specify file type upon decryption

### ISSUE THREAD

**Issue by ansuz** [UCF-project/media-tag#7]
Upon decryption of an encrypted blob which contains metadata, we would like to be able to specify the media type of the mediaObject such that it renders the appropriate data.

It should be possible to specify at an earlier time a list of media types which are allowed. For example, image, video, pdf, audio.

**Comment by Regzox** [comment]
You can set allowed plugins types like this at bundling time now (inside `/src/presets/static/media-tag.js`)
Other types does not effect on mediaObject metadata affectation and the processing engine should fall, by lack of data, in the default rendering.

`CryptoFilter.setAllowedMediaTypes([
	'image',
	'audio',
	'video',
	'pdf',
	'dash']);
`

You can now declare a configuration and modify permission before bringing it back to `MediaTag.processingEngine`. 

It forbids at ProcessingEngine level a plugin usage. The result is still a non rendering. 
`
const Configuration = require('../../core/configuration');
const Permission = require('../../enums/permission');
const Identifier = require('../../enums/identifier');

const configuration = new Configuration();

configuration.setPermission(Identifier.IMAGE, Permission.FORBIDDEN);
MediaTag.processingEngine.configure(configuration);
`
